dist: bionic

_e2e_tests: &e2e_tests
  env: 
    - CACHE_NAME=e2e_tests
    - IMAGE=pionwebrtc/ion-e2e-test
    - VERSION=v0.1.1c
  services: docker
  before_install:
    - docker pull ${IMAGE}:${VERSION}
  script:
    - mkdir ${HOME}/.cache/e2e || true
    - ls -al ${HOME}/.cache/e2e
    - |
      timeout 1200 docker run \
        -e JOB_ID=${TRAVIS_BUILD_ID} \
        -e LINODE_KEY=${LINODE_PION_ION_DEV} \
        -e LINODE_DOMAIN_ID=${LINODE_PION_ION_DOMAIN_ID} \
        -e BROWSERSTACK_URL=${PION_BROWSERSTACK_URL} \
        -e WEB_VERSION=${TRAVIS_COMMIT} \
        -e MULTI=windows/chrome,windows/firefox,mac/chrome,mac/firefox \
        -v ${HOME}/.cache/e2e:/data \
        ${IMAGE}:${VERSION} bash /test/00-main.sh
  after_script:
    - ls -al ${HOME}/.cache/e2e
    - mkdir ${HOME}/.cache/e2e || true
    - |
      docker run \
        -e JOB_ID=${TRAVIS_BUILD_ID} \
        -e LINODE_KEY=${LINODE_PION_ION_DEV} \
        -e LINODE_DOMAIN_ID=${LINODE_PION_ION_DOMAIN_ID} \
        -v ${HOME}/.cache/e2e:/data \
        ${IMAGE}:${VERSION} bash /test/99-cleanup.sh

jobs:
  include:
    - <<: *e2e_tests
      name: End-to-end browser tests
      if: branch = master OR tag IS present

notifications:
  email: false

